"""DEFLATE-D source-to-source transforms and pipeline assembly."""

from __future__ import annotations

from .base import Tier, Transform, parse_tier
from .contextual import (
    AddressOfIndexToOffset,
    CompressFunctionNames,
    CompressPlaceholderNames,
    DropNullPointerCast,
    SimplifyLowConfidenceTypes,
    StripPointerSlotAddress,
    TrimPieceAccessSuffix,
)
from .cosmetic import (
    CollapseBlankLines,
    CollapseInlineSpaces,
    CollapseLineBreaks,
    StripIndentation,
    StripTrailingWhitespace,
    TightenCommentSpaces,
    TightenWhitespace,
)
from .pipeline import Pipeline, ORDERED_TRANSFORMS, build_pipeline, transform
from .reductive import (
    DropCodePointerCast,
    DropCrtFunctions,
    ElideThunkBodies,
    EraseResolverStubs,
    RemoveWarningComments,
    StripCallingConventions,
    StripChkSuffix,
    StripConstQualifier,
    StripTranslationWrappers,
    StripWidthCasts,
    TrimSpuriousArgs,
)
from .structural import (
    CanonicalizeControlFlow,
    CoalesceDeclarations,
    CompoundAssignment,
    DerefOffsetToIndex,
    DropSingleStatementBraces,
    DropTrailingReturn,
    InlineSingleUseTemps,
    MinimizeIntegerLiterals,
    NormalizeFlagTemps,
    RedundantCastElision,
    RemoveComments,
    TernaryFromIfElse,
)

__all__ = [
    "Tier",
    "Pipeline",
    "Transform",
    "parse_tier",
    "ORDERED_TRANSFORMS",
    "build_pipeline",
    "transform",
    "CollapseBlankLines",
    "CollapseInlineSpaces",
    "CollapseLineBreaks",
    "StripIndentation",
    "StripTrailingWhitespace",
    "TightenCommentSpaces",
    "TightenWhitespace",
    "CanonicalizeControlFlow",
    "CoalesceDeclarations",
    "CompoundAssignment",
    "DerefOffsetToIndex",
    "DropSingleStatementBraces",
    "DropTrailingReturn",
    "InlineSingleUseTemps",
    "MinimizeIntegerLiterals",
    "NormalizeFlagTemps",
    "RedundantCastElision",
    "RemoveComments",
    "TernaryFromIfElse",
    "AddressOfIndexToOffset",
    "CompressFunctionNames",
    "CompressPlaceholderNames",
    "DropNullPointerCast",
    "SimplifyLowConfidenceTypes",
    "StripPointerSlotAddress",
    "TrimPieceAccessSuffix",
    "DropCodePointerCast",
    "DropCrtFunctions",
    "ElideThunkBodies",
    "EraseResolverStubs",
    "RemoveWarningComments",
    "StripCallingConventions",
    "StripChkSuffix",
    "StripConstQualifier",
    "StripTranslationWrappers",
    "StripWidthCasts",
    "TrimSpuriousArgs",
]
